
package MenuComponent;

import Core.PlayerVsPlayer;
import GUI.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author Truc Quyen
 */
public class PlayerNames extends JFrame {

    /**
     * Creates new form Options
     */
    public Boolean checkCLose = false;
    public String pn1, pn2;
    public PlayerNames() {

        setIconImage(Toolkit.getDefaultToolkit().getImage(Parameter.logo));
        setTitle("Reversi PlayerInput");
        initComponents();
//        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        player1Jlabel = new javax.swing.JLabel();
        player2Jlabel = new javax.swing.JLabel();
        titleJlabel = new javax.swing.JLabel();
        name1JTextField = new javax.swing.JTextField();
        name2JTextField = new javax.swing.JTextField();
        saveJbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        player1Jlabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        player1Jlabel.setForeground(new java.awt.Color(255, 102, 102));
        player1Jlabel.setText("Player 1");

        player2Jlabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        player2Jlabel.setForeground(new java.awt.Color(255, 102, 102));
        player2Jlabel.setText("Player 2");

        titleJlabel.setBackground(new java.awt.Color(0, 0, 0));
        titleJlabel.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        titleJlabel.setForeground(new java.awt.Color(255, 51, 102));
        titleJlabel.setText("PLAYER NAMES");

        name1JTextField.setBackground(new java.awt.Color(255, 204, 204));
        name1JTextField.setForeground(new java.awt.Color(0, 0, 0));
        name1JTextField.setText("     Input Player 1 name's:    ");
        name1JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1JTextFieldActionPerformed(evt);
            }
        });


        name1JTextField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (name1JTextField.getText().equals("     Input Player 1 name's:    "))
                    name1JTextField.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (name1JTextField.getText().equals(""))
                    name1JTextField.setText("     Input Player 1 name's:    ");
            }
        });


        name2JTextField.setBackground(new java.awt.Color(255, 204, 204));
        name2JTextField.setForeground(new java.awt.Color(0, 0, 0));
        name2JTextField.setText("     Input Player 2 name's:    ");
        name2JTextField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (name2JTextField.getText().equals("     Input Player 2 name's:    "))
                    name2JTextField.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (name2JTextField.getText().equals(""))
                    name2JTextField.setText("     Input Player 2 name's:    ");
            }
        });
        saveJbutton.setBackground(new java.awt.Color(255, 102, 102));
        saveJbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveJbutton.setForeground(new java.awt.Color(0, 0, 0));
        saveJbutton.setText("SAVE");
        saveJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJbuttonActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(Parameter.path + "\\icons8_autograph_20px_1.png")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(Parameter.path + "\\icons8_autograph_20px_1.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleJlabel)
                .addGap(230, 230, 230))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(player2Jlabel)
                            .addComponent(player1Jlabel))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name1JTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name2JTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addComponent(saveJbutton)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(titleJlabel)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(player1Jlabel)
                        .addComponent(name1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(player2Jlabel)))
                .addGap(57, 57, 57)
                .addComponent(saveJbutton)
                .addGap(299, 299, 299)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name1JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1JTextFieldActionPerformed
        // TODO add your handling code here:
           name1JTextField.setText("");
    }//GEN-LAST:event_name1JTextFieldActionPerformed

    public void saveJbuttonActionPerformed(java.awt.event.ActionEvent evt) {
        pn1 = name1JTextField.getText();
        pn2 = name2JTextField.getText();
        System.out.println(pn1);
        Parameter.player1 = pn1;
        Parameter.player2 = pn2;
//        this.dispose();
        checkCLose = true;
        System.out.println(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerNames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField name1JTextField;
    private javax.swing.JTextField name2JTextField;
    private javax.swing.JLabel player1Jlabel;
    private javax.swing.JLabel player2Jlabel;
    private javax.swing.JButton saveJbutton;
    private javax.swing.JLabel titleJlabel;
    // End of variables declaration//GEN-END:variables
}
